namespace SpriteKind {
    export const Boss = SpriteKind.create()
    export const PlayerProjectile = SpriteKind.create()
    export const StatusBarPlace = SpriteKind.create()
}
sprites.onCreated(SpriteKind.PlayerProjectile, function (sprite) {
    sprite.setPosition(mySprite.x, mySprite.y)
    sprite.setVelocity(playerDirection, 0)
    sprite.setFlag(SpriteFlag.DestroyOnWall, true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    HealthBar.value += -1
    if (HealthBar.value <= 0) {
        game.over(false)
        mySprite2.setImage(img`
            ...ffffffffff...
            ...f1111111ff...
            ...ff1111119f...
            ...f911ff1199...
            ...991f22f1199..
            ...91f2222f1f9..
            ...9fffffffff9..
            ...9...f........
            ...9...f........
            .......f......f.
            ff....ff...ffff.
            ff....ff..f...ff
            ..f..fff.f...fff
            ..f..ffff..9.ff.
            ..f..fff...9.f..
            ...ff.ff....f.ff
            ......fff...ff..
            ........f..f....
            ........f.......
            .......f........
            ..9....f........
            .......f........
            .......f........
            .......f........
            .......f........
            .......f..9.....
            ..9....f........
            .......f........
            .......f........
            .......f........
            .......f........
            ......f.........
            .9...f..........
            .9..f....9......
            ...ff....9......
            ...f............
            ...f............
            ...f............
            ....f...........
            ....f...........
            .....ff.....9...
            ......f......9..
            .......f........
            .......f........
            .9.....f........
            .9......f.......
            .9......f.......
            .........f......
            .........f......
            ........ff......
            ........f.......
            .......ff.......
            ......ff........
            ......f.........
            ......f.........
            ......f.........
            .....fff........
            ....ff..fff.....
            ...ff.....f.....
            ..ff.......ff...
            .fff........ff..
            f.f..........f..
            ..f..........f..
            .............f..
            `)
    }
})
sprites.onOverlap(SpriteKind.Boss, SpriteKind.PlayerProjectile, function (sprite, otherSprite) {
    BossBar.value += -1
    if (BossBar.value <= 0) {
        game.over(true)
        mySprite2.setImage(img`
            ...ffffffffff...
            ...f1111111ff...
            ...ff1111119f...
            ...f911ff1199...
            ...991f22f1199..
            ...91f2222f1f9..
            ...9fffffffff9..
            ...9...f........
            ...9...f........
            .......f......f.
            ff....ff...ffff.
            ff....ff..f...ff
            ..f..fff.f...fff
            ..f..ffff..9.ff.
            ..f..fff...9.f..
            ...ff.ff....f.ff
            ......fff...ff..
            ........f..f....
            ........f.......
            .......f........
            ..9....f........
            .......f........
            .......f........
            .......f........
            .......f........
            .......f..9.....
            ..9....f........
            .......f........
            .......f........
            .......f........
            .......f........
            ......f.........
            .9...f..........
            .9..f....9......
            ...ff....9......
            ...f............
            ...f............
            ...f............
            ....f...........
            ....f...........
            .....ff.....9...
            ......f......9..
            .......f........
            .......f........
            .9.....f........
            .9......f.......
            .9......f.......
            .........f......
            .........f......
            ........ff......
            ........f.......
            .......ff.......
            ......ff........
            ......f.........
            ......f.........
            ......f.........
            .....fff........
            ....ff..fff.....
            ...ff.....f.....
            ..ff.......ff...
            .fff........ff..
            f.f..........f..
            ..f..........f..
            .............f..
            `)
    }
})
sprites.onCreated(SpriteKind.Projectile, function (sprite) {
    sprite.setPosition(mySprite2.x, mySprite2.y)
    if (DirectionBossy == -1) {
        sprite.setVelocity(-50, 0)
    } else {
        sprite.setVelocity(50, 0)
    }
    sprite.setFlag(SpriteFlag.DestroyOnWall, true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Boss, function (sprite, otherSprite) {
    HealthBar.value += -1
    if (HealthBar.value <= 0) {
        game.over(false)
        mySprite2.setImage(img`
            ...ffffffffff...
            ...f1111111ff...
            ...ff1111119f...
            ...f911ff1199...
            ...991f22f1199..
            ...91f2222f1f9..
            ...9fffffffff9..
            ...9...f........
            ...9...f........
            .......f......f.
            ff....ff...ffff.
            ff....ff..f...ff
            ..f..fff.f...fff
            ..f..ffff..9.ff.
            ..f..fff...9.f..
            ...ff.ff....f.ff
            ......fff...ff..
            ........f..f....
            ........f.......
            .......f........
            ..9....f........
            .......f........
            .......f........
            .......f........
            .......f........
            .......f..9.....
            ..9....f........
            .......f........
            .......f........
            .......f........
            .......f........
            ......f.........
            .9...f..........
            .9..f....9......
            ...ff....9......
            ...f............
            ...f............
            ...f............
            ....f...........
            ....f...........
            .....ff.....9...
            ......f......9..
            .......f........
            .......f........
            .9.....f........
            .9......f.......
            .9......f.......
            .........f......
            .........f......
            ........ff......
            ........f.......
            .......ff.......
            ......ff........
            ......f.........
            ......f.........
            ......f.........
            .....fff........
            ....ff..fff.....
            ...ff.....f.....
            ..ff.......ff...
            .fff........ff..
            f.f..........f..
            ..f..........f..
            .............f..
            `)
    }
})
let mySprite6: Sprite = null
let imnotgoinghardonmyself = 0
let mySprite3: Sprite = null
let DirectionBossy = 0
let BossBar: StatusBarSprite = null
let HealthBar: StatusBarSprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
let playerDirection = 0
playerDirection = 50
mySprite = sprites.create(img`
    . . . f f f f f f f f f f . . . 
    . . . f d d d d d d d d f . . . 
    . . . f d d d d d d d d f . . . 
    . . . f d f d f f d f d f . . . 
    . . . f d d d d d d d d f . . . 
    . . . f d d d d d d d d f . . . 
    . . . f d d d d d d d d f . . . 
    . f f f f f f f f f f f f f f . 
    . f 4 f 4 4 4 4 4 4 4 4 f 4 f . 
    . f 4 f 4 4 5 5 5 5 4 4 f 4 f . 
    . f 4 f 4 5 5 4 4 4 4 4 f 4 f . 
    . f 4 f 4 5 5 4 4 5 4 4 f 4 f . 
    . f 4 f 4 4 5 5 5 5 4 4 f 4 f . 
    . f 4 f 4 4 4 4 4 4 4 4 f 4 f . 
    . f f f f f f f f f f f f f f . 
    . . . f 4 f . . . . f 4 f . . . 
    . . . f 4 f . . . . f 4 f . . . 
    . . . f f f . . . . f f f . . . 
    `, SpriteKind.Player)
mySprite2 = sprites.create(img`
    ...ffffffffff...
    ...f1111111ff...
    ...ff1111111f...
    ...f1f111f11f...
    ...f11f1f111f...
    ...f111f1111f...
    ...ffffffffff...
    .......f........
    .......f........
    .......f......f.
    ff....ff...ffff.
    ff....ff..f...ff
    ..f..fff.f...fff
    ..f..ffff....ff.
    ..f..fff.....f..
    ...ff.ff....f.ff
    ......fff...ff..
    ........f..f....
    ........f.......
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    .......f........
    ......f.........
    .....f..........
    ....f...........
    ...ff...........
    ...f............
    ...f............
    ...f............
    ....f...........
    ....f...........
    .....ff.........
    ......f.........
    .......f........
    .......f........
    .......f........
    ........f.......
    ........f.......
    .........f......
    .........f......
    ........ff......
    ........f.......
    .......ff.......
    ......ff........
    ......f.........
    ......f.........
    ......f.........
    .....fff........
    ....ff..fff.....
    ...ff.....f.....
    ..ff.......ff...
    .fff........ff..
    f.f..........f..
    ..f..........f..
    .............f..
    `, SpriteKind.Boss)
let mySprite4 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.StatusBarPlace)
let mySprite5 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.StatusBarPlace)
HealthBar = statusbars.create(20, 4, StatusBarKind.Health)
BossBar = statusbars.create(1000, 4, StatusBarKind.Health)
HealthBar.value = 100
HealthBar.setColor(5, 2, 3)
BossBar.setColor(4, 15, 3)
BossBar.setBarBorder(1, 15)
HealthBar.setBarBorder(1, 15)
tiles.setTilemap(tilemap`level1`)
mySprite.setPosition(7, 72)
mySprite2.setPosition(147, 60)
mySprite.setStayInScreen(true)
mySprite4.setPosition(60, 125)
BossBar.attachToSprite(mySprite4)
mySprite5.setPosition(20, 118)
HealthBar.attachToSprite(mySprite5)
scene.cameraFollowSprite(mySprite)
BossBar.value = 5000
BossBar.setBarSize(BossBar.value, 4)
forever(function () {
    if (controller.A.isPressed()) {
        mySprite3 = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . e . . . . . . . . . . e . . 
            . e . . . . . . . . . . . . e . 
            e . . . . . . . . . . . . . . e 
            e e e e e e e e e e e e e e e e 
            e . . . . . . . . . . . . . . e 
            . e . . . . . . . . . . . . e . 
            . . e . . . . . . . . . . e . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.PlayerProjectile)
        pause(300)
    }
})
forever(function () {
    controller.moveSprite(mySprite, 100, 0)
    if (controller.up.isPressed()) {
        imnotgoinghardonmyself = -5
        for (let index = 0; index < 11; index++) {
            mySprite.y += imnotgoinghardonmyself
            imnotgoinghardonmyself += 1
            pause(50)
        }
    }
    if (controller.left.isPressed()) {
        playerDirection = -50
    }
    if (controller.right.isPressed()) {
        playerDirection = 50
    }
    if (controller.down.isPressed()) {
        mySprite.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . f f f f f f f f f f . . . 
            . f f f d d d f d d d d f f f . 
            . f 2 f d d f d f d d d f 5 f . 
            . f f f d f f d f d f d f f f . 
            . f f f f d f d f d d f f f f . 
            . f f f d d f d f d d d f f f . 
            . f 2 f d d d d d d d d f 5 f . 
            . f f f f f f f f f f f f f f . 
            . f f f f f f f f f f f f f f . 
            . . . f 1 f . . . . f 1 f . . . 
            . . . f f f . . . . f f f . . . 
            `)
    } else {
        mySprite.setImage(img`
            . . . f f f f f f f f f f . . . 
            . . . f d d d d d d d d f . . . 
            . . . f d d d d d d d d f . . . 
            . . . f d f d f f d f d f . . . 
            . . . f d d d d d d d d f . . . 
            . . . f d d d d d d d d f . . . 
            . . . f d d d d d d d d f . . . 
            . f f f f f f f f f f f f f f . 
            . f 4 f 4 4 4 4 4 4 4 4 f 4 f . 
            . f 4 f 4 4 5 5 5 5 4 4 f 4 f . 
            . f 4 f 4 5 5 4 4 4 4 4 f 4 f . 
            . f 4 f 4 5 5 4 4 5 4 4 f 4 f . 
            . f 4 f 4 4 5 5 5 5 4 4 f 4 f . 
            . f 4 f 4 4 4 4 4 4 4 4 f 4 f . 
            . f f f f f f f f f f f f f f . 
            . . . f 4 f . . . . f 4 f . . . 
            . . . f 4 f . . . . f 4 f . . . 
            . . . f f f . . . . f f f . . . 
            `)
    }
})
forever(function () {
    pause(100)
    mySprite2.vx = randint(-200, 200)
})
forever(function () {
    pause(200)
    mySprite6 = sprites.create(img`
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
        `, SpriteKind.Projectile)
})
forever(function () {
    if (mySprite2.vx < 0) {
        DirectionBossy = -1
    } else {
        DirectionBossy = 1
    }
})
forever(function () {
    if (randint(0, 10) == 5) {
        mySprite2.vy = -100
        for (let index = 0; index < 10; index++) {
            pause(100)
            mySprite2.vy += 10
        }
        mySprite2.vy = 0
    }
})
forever(function () {
    mySprite4.setPosition(scene.cameraProperty(CameraProperty.X) - 20, scene.cameraProperty(CameraProperty.Y) + 60)
    mySprite5.setPosition(scene.cameraProperty(CameraProperty.X) - 60, scene.cameraProperty(CameraProperty.Y) + 50)
})
